[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Remove any duplicate [build.environment] section
[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--version"